//
// Created by BZLZHH on 2025/2/8.
//

#ifndef MOBILEGLUES_VERSION_H

#define VERSION_DEVELOPMENT 0
#define VERSION_ALPHA 1
#define VERSION_RELEASE 2

#define MAJOR 2
#define MINOR 0
#define REVISION 0
#define PATCH 0

#define VERSION_NUM \
    (MAJOR * 1000 + MINOR * 100 + REVISION * 10 + PATCH)

#define VERSION_TYPE VERSION_DEVELOPMENT

#define VERSION_SUFFIX "-fpe"

#define MOBILEGLUES_VERSION_H

#endif //MOBILEGLUES_VERSION_H
